//! Core runtime library for Velomorph.
//!
//! **Version 1.0** stabilizes the public API (`Morph`, `TryMorph`, `MorphError`, and
//! optional `Janitor` when the `janitor` feature is enabled) for semver-compatible
//! evolution within the **1.x** line.
//!
//! This crate provides:
//! - `Morph`, a derive macro re-export for generating transformations.
//! - `TryMorph`, the trait implemented by generated code.
//! - `Janitor` (feature: `janitor`), an optional background deallocation helper.
//! - Blanket list mapping: `TryMorph<Vec<U>> for Vec<T>` when `T: TryMorph<U>`.
//!
//! Notes:
//! - Derive behavior is generated by `velomorph-derive`.
//! - Supported derive controls include: `from`, `with`, `default`, `skip`,
//!   `validate`, and enum variant remapping.
//! - `Janitor` is available to user code and to generated implementations via the
//!   `try_morph(self, &Janitor)` signature when the `janitor` feature is enabled.
//!
//! # Quick Example
//! ```ignore
//! use std::borrow::Cow;
//! use uuid::Uuid;
//! use velomorph::{Morph, TryMorph};
//! #[cfg(feature = "janitor")]
//! use velomorph::Janitor;
//!
//! pub struct RawInput<'a> {
//!     // Legacy/external names from an upstream system:
//!     pub uuid_v4: Option<Uuid>,
//!     pub user_str: &'a str,
//!     pub payload: Option<Vec<u8>>,
//! }
//!
//! #[derive(Morph, Debug)]
//! pub struct Event<'a> {
//!     // Rename `uuid_v4` -> `id` while enforcing presence:
//!     #[morph(from = "uuid_v4")]
//!     pub id: Uuid,
//!
//!     // Rename `user_str` -> `username` while borrowing the string:
//!     #[morph(from = "user_str")]
//!     pub username: Cow<'a, str>,
//! }
//!
//! #[cfg(feature = "janitor")]
//! let janitor = Janitor::new();
//! let raw = RawInput {
//!     uuid_v4: Some(Uuid::new_v4()),
//!     user_str: "edge-a",
//!     payload: Some(vec![1, 2, 3]),
//! };
//! #[cfg(feature = "janitor")]
//! let event: Event = raw.try_morph(&janitor)?;
//! #[cfg(not(feature = "janitor"))]
//! let event: Event = raw.try_morph()?;
//! # Ok::<(), velomorph::MorphError>(())
//! ```
//!
//! # List Mapping
//! You can morph whole vectors when each item supports `TryMorph`:
//! ```ignore
//! use velomorph::TryMorph;
//! # use velomorph::MorphError;
//! # struct Source;
//! # struct Target;
//! # impl TryMorph<Target> for Source {
//! #   fn try_morph(self) -> Result<Target, MorphError> { Ok(Target) }
//! # }
//! let input: Vec<Source> = vec![Source, Source];
//! let output: Vec<Target> = input.try_morph()?;
//! # Ok::<(), MorphError>(())
//! ```
//!
//! With `janitor` enabled, the same mapping accepts `&Janitor`:
//! ```ignore
//! # #[cfg(feature = "janitor")]
//! # {
//! use velomorph::{Janitor, TryMorph};
//! # use velomorph::MorphError;
//! # struct Source;
//! # struct Target;
//! # impl TryMorph<Target> for Source {
//! #   fn try_morph(self, _janitor: &Janitor) -> Result<Target, MorphError> { Ok(Target) }
//! # }
//! let janitor = Janitor::new();
//! let input: Vec<Source> = vec![Source, Source];
//! let output: Vec<Target> = input.try_morph(&janitor)?;
//! # let _ = output;
//! # }
//! ```

#[cfg(feature = "janitor")]
use std::thread;
#[cfg(feature = "janitor")]
use tokio::sync::mpsc;

/// Derive macro used to generate `TryMorph` implementations.
pub use velomorph_derive::Morph;

/// Errors that can occur while transforming an input type into a target type.
#[derive(thiserror::Error, Debug)]
pub enum MorphError {
    /// A required field was missing in the source value.
    #[error("Required field is missing: {0}")]
    MissingField(String),
    /// A post-morph validation step failed.
    #[error("Validation failed: {0}")]
    ValidationError(String),
    /// A custom transform function failed.
    #[error("Transform failed: {0}")]
    TransformError(String),
}

/// Trait for fallible transformations from a source type to `Target`.
///
/// Implementations are typically generated via `#[derive(Morph)]`.
#[cfg(not(feature = "janitor"))]
pub trait TryMorph<Target> {
    /// Attempts to transform `self` into `Target`.
    fn try_morph(self) -> Result<Target, MorphError>;
}

#[cfg(not(feature = "janitor"))]
impl<T, U> TryMorph<Vec<U>> for Vec<T>
where
    T: TryMorph<U>,
{
    fn try_morph(self) -> Result<Vec<U>, MorphError> {
        self.into_iter().map(TryMorph::try_morph).collect()
    }
}

/// Trait for fallible transformations from a source type to `Target`.
///
/// Implementations are typically generated via `#[derive(Morph)]`.
#[cfg(feature = "janitor")]
pub trait TryMorph<Target> {
    /// Attempts to transform `self` into `Target`.
    ///
    /// The `janitor` is made available to implementations when desired.
    fn try_morph(self, janitor: &Janitor) -> Result<Target, MorphError>;
}

#[cfg(feature = "janitor")]
impl<T, U> TryMorph<Vec<U>> for Vec<T>
where
    T: TryMorph<U>,
{
    fn try_morph(self, janitor: &Janitor) -> Result<Vec<U>, MorphError> {
        self.into_iter()
            .map(|item| item.try_morph(janitor))
            .collect()
    }
}

/// Background deallocation helper that minimizes latency spikes.
///
/// `Janitor` owns a channel to a dedicated thread. Large objects can be sent to
/// that thread for dropping, allowing the main path to continue with minimal
/// interruption.
///
/// # Modes
///
/// - [`Janitor::new`] and [`Default::default`] use an **unbounded** queue: no
///   backpressure; overload can grow memory without limit (see crate README).
/// - [`Janitor::bounded`] uses a **bounded** queue: at most `capacity` items wait
///   in the channel. If the queue is full, [`offload`](Janitor::offload) **drops
///   the value on the caller thread** (that call is not deferred). This caps how
///   much work can queue up without blocking an async runtime (see crate README).
#[cfg(feature = "janitor")]
#[derive(Clone)]
pub struct Janitor {
    sender: JanitorSender,
}

#[cfg(feature = "janitor")]
#[derive(Clone)]
enum JanitorSender {
    Unbounded(mpsc::UnboundedSender<Box<dyn std::any::Any + Send>>),
    Bounded(mpsc::Sender<Box<dyn std::any::Any + Send>>),
}

#[cfg(feature = "janitor")]
impl Janitor {
    /// Creates a new janitor with an **unbounded** queue and a background worker thread.
    ///
    /// This is the same as [`Default::default`].
    pub fn new() -> Self {
        let (tx, mut rx) = mpsc::unbounded_channel();

        thread::spawn(move || {
            while let Some(item) = rx.blocking_recv() {
                // Drop happens outside the latency-sensitive path.
                std::mem::drop(item);
            }
        });

        Self {
            sender: JanitorSender::Unbounded(tx),
        }
    }

    /// Creates a janitor with a **bounded** queue of the given capacity.
    ///
    /// `capacity` must be greater than zero. When the queue is full,
    /// [`offload`](Janitor::offload) drops the value on the **caller** thread
    /// instead of enqueueing it (see [`offload`](Janitor::offload)).
    ///
    /// # Panics
    ///
    /// Panics if `capacity` is zero.
    pub fn bounded(capacity: usize) -> Self {
        assert!(
            capacity > 0,
            "Janitor::bounded: capacity must be greater than zero"
        );

        let (tx, mut rx) = mpsc::channel(capacity);

        thread::spawn(move || {
            while let Some(item) = rx.blocking_recv() {
                std::mem::drop(item);
            }
        });

        Self {
            sender: JanitorSender::Bounded(tx),
        }
    }

    /// Sends an object to the background thread for deallocation.
    ///
    /// This is useful when immediate drop cost would otherwise add jitter to
    /// a critical execution path.
    ///
    /// For an **unbounded** janitor, sends never block unless the receiver is
    /// disconnected.
    ///
    /// For a **bounded** janitor, this uses a non-blocking send. If the queue is
    /// full, the value is **dropped on the caller thread** (so it is not deferred
    /// to the worker). This avoids blocking inside an async runtime (Tokio
    /// `blocking_send` is not safe to call from async worker threads) while still
    /// capping how many items can wait in the channel.
    #[inline(always)]
    pub fn offload<T: Send + 'static>(&self, item: T) {
        let boxed = Box::new(item) as Box<dyn std::any::Any + Send>;
        match &self.sender {
            JanitorSender::Unbounded(tx) => {
                let _ = tx.send(boxed);
            }
            JanitorSender::Bounded(tx) => match tx.try_send(boxed) {
                Ok(()) => {}
                Err(mpsc::error::TrySendError::Full(b)) => {
                    std::mem::drop(b);
                }
                Err(mpsc::error::TrySendError::Closed(b)) => {
                    std::mem::drop(b);
                }
            },
        }
    }
}

/// Creates a new `Janitor` using `Janitor::new()`.
#[cfg(feature = "janitor")]
impl Default for Janitor {
    fn default() -> Self {
        Self::new()
    }
}
